### ISSUE TITLE
Firework rocket store

### ISSUE THREAD

**Issue by shanemeyers** [ItzAmirreza/EzChestShop#44] opened 2023-03-10 04:31 UTC
If I create a chest store holding a crafted `firework_rocket`, it creates the store, but refuses to sell any of the inventory. I keep getting the error message of `The shop is out of stock` even when there's many stacks of rockets in the chest. The rocket that was used for this has a `Flight duration: 1` metadata attached to it.

To manually craft this type of rocket: `/give <user> firework_rocket 1 {Fireworks:{Flight:1}}`

If I give a user a rocket using `/give <user> firework_rocket` (without any metadata) and then create a chest using that given rocket, the store builds and works correctly only as long as I put `/give` provided rockets in the chest (rockets without a `Flight duration`). Rockets created by crafting will not sell from the shop.

EzChestShop - version 1.5.0

**Comment by shanemeyers** [comment] 2023-03-10 04:34
EzChestShop - version 1.5.0

**Comment by ElitoGame** [comment] 2023-03-11 16:00
Hey! As far as I can remember from my testing, rockets given via /give don't stack with rockets acquired with crafting. If that's the case and you are having a problem with trying to sell those two at the same shop, I am not sure we're able to fix this. A few items have certain hidden data elements that cause slight fluctuations. We can't look out for all the small differences, so as long as the items are not 100% identical the item won't sell.

The only possible thing, I can think of is using the item.isSimilar() method rather then item.equals(), however I haven't tested nor checked the code yet. This might also introduce other issues and Minecraft has so many items that it's hard to really test all possible metadatas for such problems.

**Comment by shanemeyers** [comment] 2023-03-14 19:32
The goal with testing rockets created by `/give` is as an example of a shop that works as expected. 

My ultimate goal is to have a shop that functions correctly for crafted rockets. One of my server users created the shop using crafted rockets and nothing will sell (he has zero access to `/give` or other op commands). As it is today, the crafted rocket shop does not work correctly. It says out of stock even though there's plenty of inventory.

I agree that Minecraft has a ton of items with varying metadata, sadly in this case it appears that metadata is applied to a crafted item at creation time, compared to most other items that can be crafted and metadata is applied later when enchanting or otherwise changing the item's behavior.

**Comment by ItzAmirreza** [comment] 2023-03-14 19:37
It would be great if we could know the metadata of the item player has in hand and the one that is inside the chest, maybe we could work on it. If you got the time, would be great to provide some info on this, so we can know where exactly it happens and which one has additional metadata. Otherwise, I will/or @ElitoGame will check this problem to get some info whenever we got the time.

**Comment by shanemeyers** [comment] 2023-03-15 22:27
If you can give me guidance on how to retrieve the metadata you're interested in, I'm willing to take the time to find and provide it.

**Comment by ItzAmirreza** [comment] 2023-03-17 09:33
Update:
I tried getting the metadata, and NBT tag but unfortunately the result is the same, and the items are identical in that shape. Still investigating...

**Comment by ItzAmirreza** [comment] 2023-05-28 15:59
Still cannot understand where's the problem - kinda given up on this, but will keep this issue open until someone more smarter than me finds the problem.

**Comment by xcina** [comment] 2023-06-28 21:55
i dont know if you guys understand the problem, it is impossible to sell fireworks with this plugin... the problem is most likeley because when crafted the firework has flight duration attached to it and when the shop is created it does not include this. somone please make when firework shop is created it uses the data of the firework.

**Comment by ElitoGame** [comment] 2023-06-28 22:30
Closed and fixed with commit https://github.com/ItzAmirreza/EzChestShop/commit/12f1e32ea6a4609afa747706bc11b0c536806293
There are some specialized limitations that only apply to firework rockets, read the commit message if affected.

**Closed by ElitoGame** 2023-06-28 22:30 UTC
Labels: bug, help wanted
